/*
 * Toy API
 *
 * Toy API for testing RESTler
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/reggieag/NYU_PCS_project/server/go"
)

func main() {
	log.Printf("Server started")

	DefaultAPIService := openapi.NewDefaultApiService()
	DefaultAPIController := openapi.NewDefaultApiController(DefaultAPIService)

	router := openapi.NewRouter(DefaultAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
