/*
 * Toy API
 *
 * Toy API for testing RESTler
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataOutput struct {

	DataId int32 `json:"dataId"`

	Name string `json:"name"`

	Quantity int32 `json:"quantity"`
}
