/*
 * Toy API
 *
 * Toy API for testing RESTler
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject1 struct {

	Name string `json:"name,omitempty"`

	Quantity int32 `json:"quantity,omitempty"`
}
