/*
 * Toy API
 *
 * Toy API for testing RESTler
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request, 
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface { 
	DataDataIdDelete(http.ResponseWriter, *http.Request)
	DataDataIdGet(http.ResponseWriter, *http.Request)
	DataDataIdPost(http.ResponseWriter, *http.Request)
	DataGet(http.ResponseWriter, *http.Request)
	DataPost(http.ResponseWriter, *http.Request)
}


// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type DefaultApiServicer interface { 
	DataDataIdDelete(context.Context, int32) (ImplResponse, error)
	DataDataIdGet(context.Context, int32) (ImplResponse, error)
	DataDataIdPost(context.Context, int32, InlineObject1) (ImplResponse, error)
	DataGet(context.Context) (ImplResponse, error)
	DataPost(context.Context, InlineObject) (ImplResponse, error)
}
